---
# tasks file for vector-role
- name: Install Python (for Ansible)
  ansible.builtin.raw: |
    if command -v apt-get >/dev/null; then
      apt-get update && apt-get install -y python3
    elif command -v yum >/dev/null; then
      yum install -y python3
    elif command -v dnf >/dev/null; then
      dnf install -y python3
    fi
  register: python_install
  changed_when: python_install.rc == 0
  become: true
- name: Download Vector package
  ansible.builtin.get_url:
    url: "{{ vector_download_url }}"
    dest: "/tmp/{{ vector_deb_package }}"
    mode: '0644'

- name: Install Vector package
  ansible.builtin.apt:
    deb: "/tmp/{{ vector_deb_package }}"

- name: Create Vector config directory
  ansible.builtin.file:
    path: "{{ vector_config_dir }}"
    state: directory
    mode: '0755'

- name: Deploy Vector configuration from template
  ansible.builtin.template:
    src: templates/vector.yml.j2
    dest: "{{ vector_config_dir }}/{{ vector_config_file }}"
    mode: '0644'
  notify: Restart Vector

- name: Start and enable Vector service
  ansible.builtin.service:
    name: vector
    state: started
    enabled: yes
