---
# tasks file for vector-role
- name: Download Vector package
  ansible.builtin.get_url:
    url: "{{ vector_download_url }}"
    dest: "/tmp/{{ vector_deb_package }}"
    mode: '0644'

- name: Install Vector package
  ansible.builtin.apt:
    deb: "/tmp/{{ vector_deb_package }}"

- name: Create Vector config directory
  ansible.builtin.file:
    path: "{{ vector_config_dir }}"
    state: directory
    mode: '0755'

- name: Deploy Vector configuration from template
  ansible.builtin.template:
    src: templates/vector.yml.j2
    dest: "{{ vector_config_dir }}/{{ vector_config_file }}"
    mode: '0644'
  notify: Restart Vector

- name: Start and enable Vector service
  ansible.builtin.service:
    name: vector
    state: started
    enabled: yes
